config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'clubs#index'
  resources :landing, only: %i[index]
  resources :tournaments, only: %i[index show]
  resources :results, only: %i[index show]
  resources :admins

  namespace :rankings do
    resource :ranks, only: %i[create] do
      post '/collect-points-job', to: 'ranks#collect_points_job'
      post '/create-players-with-points-job', to: 'ranks#create_players_with_points_job'
    end
    resources :singles, only: %i[index]
    resources :doubles, only: %i[index]
    resources :womens_singles, only: %i[index]
    resources :womens_doubles, only: %i[index]
  end

  # resources :local_tournaments, only: %i[index new]
  resources :photos, only: %i[index show create new destroy]
  resources :hall_of_fames, only: %i[index]
  resources :rules, only: %i[index]
  resources :local_tournaments, only: :index
  resources :clubs, only: %i[index new show create] do
    resources :local_tournaments, only: %i[new show edit create destroy] do
      resources :participants, only: %i[create destroy]
      get '/generate-tournament', to: 'local_tournaments#generate_tournament', as: :generate_tournament
      get '/start-tournament', to: 'local_tournaments#start_tournament', as: :start_tournament
      post '/enter-match-result/:match_id', to: 'local_tournaments#enter_match_result', as: :enter_match_result
      post '/finalize', to: 'local_tournaments#finalize', as: :finalize
      post '/submit-winner', to: 'local_tournaments#submit_winner'
    end
  end
  resources :players, only: %i[index new create show edit update]

  get '/404',       to: 'errors#not_found',             as: :not_found
  get '/500',       to: 'errors#internal_server_error', as: :internal_server_error
  get '/422',       to: 'errors#unprocessable_entity',  as: :unprocessable_entity
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# rubocop:enable Metrics/BlockLength

app/controllers/rankings/doubles_controller.rb
module Rankings
  class DoublesController < ApplicationController
    def index
      players = Player.all
      if params[:term].present?
        @search = true
        players_result = players.where("first_name || ' ' || last_name ILIKE ?", "%#{params[:term]}%")
                                .joins(:ranking_detail)
                                .order('ranking_details.doubles_points desc')
      else
        players_result = players.joins(:ranking_detail)
                                .order('ranking_details.doubles_points desc')
      end
      if params[:rank_class].present?
        players_result = players_result.joins(:ranking_detail).where('ranking_details.doubles_rank = ?', params[:rank_class])
      end
      @players = players_result.page params[:page]
    end
  end
end

app/controllers/rankings/ranks_controller.rb
module Rankings
  class RanksController < ApplicationController
    def create
      # Delayed::Job.enqueue PlayerRankingJob.new
      # redirect_back fallback_location: root_path, notice: 'Re-ranking players. Could take a moment.'
    end

    # def collect_points_job
      # return unless Rails.env.development?

      # Delayed::Job.enqueue CollectPlayerPointsJob.new
      # redirect_back fallback_location: root_path, notice: 'Collecting player points. Could take hours.'
    # end

    # def create_players_with_points_job
    #   Delayed::Job.enqueue(CreatePlayersWithPointsJob.new)
    #   redirect_back fallback_location: root_path, notice: 'Creating players. Could take a moment.'
    # end
  end
end

app/controllers/rankings/singles_controller.rb
module Rankings
  class SinglesController < ApplicationController
    def index
      players = Player.all
      if params[:term].present?
        @search = true
        players_result = players.where("first_name || ' ' || last_name ILIKE ?", "%#{params[:term]}%")
                                .joins(:ranking_detail)
                                .order('ranking_details.singles_position asc')
      else
        players_result = players.joins(:ranking_detail)
                                .order('ranking_details.singles_position asc')
      end
      if params[:rank_class].present?
        players_result = players_result.joins(:ranking_detail).where('ranking_details.singles_rank = ?', params[:rank_class])
      end
      @players = players_result.page params[:page]
    end
  end
end

app/controllers/rankings/womens_doubles_controller.rb
module Rankings
  class WomensDoublesController < ApplicationController
    def index
      players = Player.where(gender: 'F')
      if params[:term].present?
        @search = true
        players_result = players.where("first_name || ' ' || last_name ILIKE ?", "%#{params[:term]}%")
                                .joins(:ranking_detail)
                                .order('ranking_details.womens_doubles_position asc')
      else
        players_result = players.joins(:ranking_detail)
                                .order('ranking_details.womens_doubles_position asc')
      end
      if params[:rank_class].present?
        players_result = players_result.joins(:ranking_detail).where('ranking_details.womens_doubles_rank = ?', params[:rank_class])
      end
      @players = players_result.page params[:page]
    end
  end
end

app/controllers/rankings/womens_singles_controller.rb
module Rankings
  class WomensSinglesController < ApplicationController
    def index
      players = Player.where(gender: 'F')
      if params[:term].present?
        @search = true
        players_result = players.where("first_name || ' ' || last_name ILIKE ?", "%#{params[:term]}%")
                                .joins(:ranking_detail)
                                .order('ranking_details.womens_singles_position asc')
      else
        players_result = players.joins(:ranking_detail)
                                .order('ranking_details.womens_singles_position asc')
      end
      if params[:rank_class].present?
        players_result = players_result.joins(:ranking_detail).where('ranking_details.womens_singles_rank = ?', params[:rank_class])
      end
      @players = players_result.page params[:page]
    end
  end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_player_list.html.slim
.container
  .row.table-header.py-4.mx-1
    .col-2.col-sm-1 Rank
    .col-5.col-sm-4 Name
    .col-3.col-sm-2 Class
    .col-3.col-sm-2.d-none.d-sm-block.text-center State/Region
    .col-3.col-sm-2.d-none.d-md-block.text-center Gender
    .col-2.col-sm-1.text-right Points
  - if @players.empty?
    p.py-3.text-center No Results Found

  - @players.each do |player|
    .row.py-3.mx-1.table-row.clickable-row data-link="#{player_path(player[:id])}"
      .col-2.col-sm-1 = player.ranking_detail.try("#{controller_name}_position".to_sym)
      .col-5.col-sm-4 = player.full_name.titleize
      .col-3.col-sm-2 = player.ranking_detail.try("#{controller_name}_rank".to_sym)
      .col-3.col-sm-2.d-none.d-sm-block.text-center = player.state
      .col-3.col-sm-2.d-none.d-md-block.text-center = player.gender
      .col-2.col-sm-1.text-right = player.ranking_detail.try("#{controller_name}_points".to_sym)
  .d-sm-none
    = paginate @players, window: 1, theme: 'twitter-bootstrap-4'
  .d-none.d-sm-block.d-md-none
    = paginate @players, window: 2, theme: 'twitter-bootstrap-4'
  .d-none.d-md-block
    = paginate @players, window: 3, theme: 'twitter-bootstrap-4'


javascript:
  $(".clickable-row").click(function() {
  window.location = $(this).data("link")
  })

app/views/rankings/_search_box.html.slim
.container.pt-4.pb-3
  = form_tag(send("rankings_#{controller_name}_path"), method: :get) do
    - if current_user.try(:admin?)
      .search-item.button
          = link_to "new player", new_player_path, class: 'btn btn-outline-primary'
      / .search-item.button
        / = link_to "re-rank all players", rankings_ranks_path, method: :post, class: 'btn btn-outline-primary'
    .search-item.button.dropdown
      = select_tag :rank_class, options_for_select(RankingDetail::RANKS.map(&:titleize), selected: params[:rank_class]), { include_blank: 'all classes', class: 'btn btn-outline-primary dropdown-toggle class-filter', id: 'RankingClassSelector'}
    .search-item.search-box
      = text_field_tag :term, params[:term], placeholder: 'search', class: 'input'
      button type="submit"
        i.fa.fa-search
      - if @search
        = link_to send("rankings_#{controller_name}_path") do
          i.fa.fa-times