config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'clubs#index'
  resources :landing, only: %i[index]
  resources :tournaments, only: %i[index show]
  resources :results, only: %i[index show]
  resources :admins

  namespace :rankings do
    resource :ranks, only: %i[create] do
      post '/collect-points-job', to: 'ranks#collect_points_job'
      post '/create-players-with-points-job', to: 'ranks#create_players_with_points_job'
    end
    resources :singles, only: %i[index]
    resources :doubles, only: %i[index]
    resources :womens_singles, only: %i[index]
    resources :womens_doubles, only: %i[index]
  end

  # resources :local_tournaments, only: %i[index new]
  resources :photos, only: %i[index show create new destroy]
  resources :hall_of_fames, only: %i[index]
  resources :rules, only: %i[index]
  resources :local_tournaments, only: :index
  resources :clubs, only: %i[index new show create] do
    resources :local_tournaments, only: %i[new show edit create destroy] do
      resources :participants, only: %i[create destroy]
      get '/generate-tournament', to: 'local_tournaments#generate_tournament', as: :generate_tournament
      get '/start-tournament', to: 'local_tournaments#start_tournament', as: :start_tournament
      post '/enter-match-result/:match_id', to: 'local_tournaments#enter_match_result', as: :enter_match_result
      post '/finalize', to: 'local_tournaments#finalize', as: :finalize
      post '/submit-winner', to: 'local_tournaments#submit_winner'
    end
  end
  resources :players, only: %i[index new create show edit update]

  get '/404',       to: 'errors#not_found',             as: :not_found
  get '/500',       to: 'errors#internal_server_error', as: :internal_server_error
  get '/422',       to: 'errors#unprocessable_entity',  as: :unprocessable_entity
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_errors.html.slim
- object.errors.messages[:base].each do |error|
  - content_for :alert
    = error

app/views/shared/_global_nav.html.slim
nav.navbar.navbar-toggleable-md.navbar-light.navbar-expand-md.bg-faded.sticky-top.main-nav
  button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  = link_to image_tag('pft.png', class: 'logo-image'), root_path
  .collapse.navbar-collapse id="navbarNavDropdown"
    ul.navbar-nav
      / li.nav-item.dropdown
      /   = link_to 'TOURNAMENTS', '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdownTournamentsLink', 'data-toggle': 'dropdown', 'aria-haspopup': 'true'
      /   .dropdown-menu aria-labelledby="navbarDropdownTournamentsLink"
      /     = link_to 'TOUR TOURNAMENTS', tournaments_path, class: 'dropdown-item'
      /     = link_to 'LOCAL TOURNAMENTS', local_tournaments_path, class: 'dropdown-item'
      / - if ENV['USE_RESULTS'] == 'true'
      /   li.nav-item
      /     = link_to 'RESULTS', results_path, class: 'nav-link'
      / li.nav-item.dropdown
      /   = link_to 'PLAYER RANKINGS', '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdownMenuLink', 'data-toggle': 'dropdown', 'aria-haspopup': 'true'
      /   .dropdown-menu aria-labelledby="navbarDropdownMenuLink"
      /     = link_to 'SINGLES', rankings_singles_path, class: 'dropdown-item'
      /     = link_to 'DOUBLES', rankings_doubles_path, class: 'dropdown-item'
      /     = link_to 'WOMENS SINGLES', rankings_womens_singles_path, class: 'dropdown-item'
      /     = link_to 'WOMENS DOUBLES', rankings_womens_doubles_path, class: 'dropdown-item'
      - if ENV['USE_PHOTOS'] == 'true'
        li.nav-item
          = link_to 'PHOTOS', photos_path, class: 'nav-link'
      - if ENV['USE_HALL_OF_FAME'] == 'true'
        li.nav-item
          = link_to 'HALL OF FAME', hall_of_fames_path, class: 'nav-link'
      li.nav-item
        = link_to 'FOOSBALL CLUBS', clubs_path, class: 'nav-link'

app/views/shared/_small_nav.html.slim
ul.small-nav
  li = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'items' if user_signed_in?
  - unless user_signed_in?
    li = link_to 'sign in', new_user_session_path, class: 'items'
  / - if current_user.try(:admin)
  /   li = link_to 'Admin Menu', admins_path, class: 'items'
  li.title.text-center Pro Foosball Tour