config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'clubs#index'
  resources :landing, only: %i[index]
  resources :tournaments, only: %i[index show]
  resources :results, only: %i[index show]
  resources :admins

  namespace :rankings do
    resource :ranks, only: %i[create] do
      post '/collect-points-job', to: 'ranks#collect_points_job'
      post '/create-players-with-points-job', to: 'ranks#create_players_with_points_job'
    end
    resources :singles, only: %i[index]
    resources :doubles, only: %i[index]
    resources :womens_singles, only: %i[index]
    resources :womens_doubles, only: %i[index]
  end

  # resources :local_tournaments, only: %i[index new]
  resources :photos, only: %i[index show create new destroy]
  resources :hall_of_fames, only: %i[index]
  resources :rules, only: %i[index]
  resources :local_tournaments, only: :index
  resources :clubs, only: %i[index new show create] do
    resources :local_tournaments, only: %i[new show edit create destroy] do
      resources :participants, only: %i[create destroy]
      get '/generate-tournament', to: 'local_tournaments#generate_tournament', as: :generate_tournament
      get '/start-tournament', to: 'local_tournaments#start_tournament', as: :start_tournament
      post '/enter-match-result/:match_id', to: 'local_tournaments#enter_match_result', as: :enter_match_result
      post '/finalize', to: 'local_tournaments#finalize', as: :finalize
      post '/submit-winner', to: 'local_tournaments#submit_winner'
    end
  end
  resources :players, only: %i[index new create show edit update]

  get '/404',       to: 'errors#not_found',             as: :not_found
  get '/500',       to: 'errors#internal_server_error', as: :internal_server_error
  get '/422',       to: 'errors#unprocessable_entity',  as: :unprocessable_entity
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# rubocop:enable Metrics/BlockLength

app/models/player.rb
class Player < ApplicationRecord
  paginates_per 50
  has_one :ranking_detail, dependent: :destroy

  accepts_nested_attributes_for :ranking_detail, allow_destroy: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true

  scope :female, -> { where(gender: 'F') }
  scope :male, -> { where(gender: 'M') }

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate, only: [:new, :create]

  def new
    @player = Player.new
    @player.build_ranking_detail
  end

  def edit
    @player = Player.find(params[:id])
  end

  def show
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to rankings_singles_path
    else
      render 'new'
    end
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to rankings_singles_path
    else
      render 'edit'
    end
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name, :gender, :state,
                                   ranking_detail_attributes: [:id, :player_id, :singles_points, :doubles_points, :womens_singles_points, :womens_doubles_points])
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.slim
= simple_form_for @player do |f|
  .error.pb-2 = f.error_notification
  .row
    .col-12.col-sm-6.form-group
      = f.input_field :first_name, placeholder: 'First Name', class: 'form-control'
      .error = f.error :first_name
    .col-12.col-sm-6.form-group
      = f.input_field :last_name, placeholder: 'Last Name', class: 'form-control'
      .error = f.error :last_name
    .col-12.col-sm-6.form-group
      = f.collection_select :gender, ["M", "F"], :to_s, :to_s,{ include_blank: 'Gender' }, { class: 'form-control', id: 'gender-selector' }
      .error = f.error :gender
    .col-12.col-sm-6.form-group
      = f.text_field :state, placeholder: 'State', class: 'form-control'

    = f.simple_fields_for :ranking_detail do |d|
      .col-12.col-sm-6.form-group
        = d.input_field :singles_points, placeholder: 'Singles Points', class: 'form-control'
        .error = d.error :singles_points
      .col-12.col-sm-6.form-group
        = d.input_field :doubles_points, placeholder: 'Doubles Points', class: 'form-control'
        .error = d.error :doubles_points
      .col-12.col-sm-6.form-group
        = d.input_field :womens_singles_points, placeholder: 'Womens Singles Points', class: 'form-control womens-points hide'
        .error = d.error :womens_singles_points
      .col-12.col-sm-6.form-group
        = d.input_field :womens_doubles_points, placeholder: 'Womens Doubles Points', class: 'form-control womens-points hide'
        .error = d.error :womens_doubles_points
      .col-12.form-group
        = f.submit 'submit', class: 'btn btn-outline-primary green-outline w-100'

app/views/players/edit.html.slim
.container.pt-4
  h3.text-center = "Edit #{@player.full_name}"

  = render 'form'

app/views/players/new.html.slim
- provide(:title, 'New Player')
.container.pt-4
  h3.text-center New Player

  = render 'form'

app/views/players/show.html.slim
.container
  h3.text-center.py-4 = @player.full_name
  .row
    .col-3 Singles Rank
    .col-3 = @player.ranking_detail.singles_position
  .row
    .col-3 Singles Class
    .col-3 = @player.ranking_detail.singles_rank
  .row
    .col-3 Singles Points
    .col-3 = @player.ranking_detail.singles_points
  .row
    .col-3 Doubles Rank
    .col-3 = @player.ranking_detail.doubles_position
  .row
    .col-3 Doubles Class
    .col-3 = @player.ranking_detail.doubles_rank
  .row
    .col-3 Doubles Points
    .col-3 = @player.ranking_detail.doubles_points
  - if @player.ranking_detail.womens_singles_points.present?
    .row
      .col-3 Women's Singles Rank
      .col-3 = @player.ranking_detail.womens_singles_position
    .row
      .col-3 Women's Singles Class
      .col-3 = @player.ranking_detail.womens_singles_rank
    .row
      .col-3 Women's Singles Points
      .col-3 = @player.ranking_detail.womens_singles_points
    .row
      .col-3 Women's Doubles Rank
      .col-3 = @player.ranking_detail.womens_doubles_position
    .row
      .col-3 Women's Doubles Class
      .col-3 = @player.ranking_detail.womens_doubles_rank
    .row
      .col-3 Women's Doubles Point
      .col-3 = @player.ranking_detail.womens_doubles_points

  .button
    = link_to "edit player", edit_player_path, class: 'btn btn-outline-primary' if current_user.try(:admin?)