config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'clubs#index'
  resources :landing, only: %i[index]
  resources :tournaments, only: %i[index show]
  resources :results, only: %i[index show]
  resources :admins

  namespace :rankings do
    resource :ranks, only: %i[create] do
      post '/collect-points-job', to: 'ranks#collect_points_job'
      post '/create-players-with-points-job', to: 'ranks#create_players_with_points_job'
    end
    resources :singles, only: %i[index]
    resources :doubles, only: %i[index]
    resources :womens_singles, only: %i[index]
    resources :womens_doubles, only: %i[index]
  end

  # resources :local_tournaments, only: %i[index new]
  resources :photos, only: %i[index show create new destroy]
  resources :hall_of_fames, only: %i[index]
  resources :rules, only: %i[index]
  resources :local_tournaments, only: :index
  resources :clubs, only: %i[index new show create] do
    resources :local_tournaments, only: %i[new show edit create destroy] do
      resources :participants, only: %i[create destroy]
      get '/generate-tournament', to: 'local_tournaments#generate_tournament', as: :generate_tournament
      get '/start-tournament', to: 'local_tournaments#start_tournament', as: :start_tournament
      post '/enter-match-result/:match_id', to: 'local_tournaments#enter_match_result', as: :enter_match_result
      post '/finalize', to: 'local_tournaments#finalize', as: :finalize
      post '/submit-winner', to: 'local_tournaments#submit_winner'
    end
  end
  resources :players, only: %i[index new create show edit update]

  get '/404',       to: 'errors#not_found',             as: :not_found
  get '/500',       to: 'errors#internal_server_error', as: :internal_server_error
  get '/422',       to: 'errors#unprocessable_entity',  as: :unprocessable_entity
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# rubocop:enable Metrics/BlockLength

app/models/local_tournament.rb
# rubocop:disable Metrics/ClassLength
class LocalTournament < ApplicationRecord
  serialize :tournament_hash
  serialize :results_hash
  enum format: %i[singles double_draw_your_partner single_draw_your_partner draw_your_partner_bring_your_partner single_bring_your_partner]

  enum status: {
    signing_up: 'signing_up',
    started: 'started',
    finished: 'finished'
  }

  belongs_to :club

  validates :name, presence: true
  validates :format, presence: true
  validate :participants_count_is_ok
  validate :participants_names_are_unique

  after_create :create_unique_url
  after_destroy :destroy_challonge_tournament

  ELIMINATIONS = [['single elimination', 'single_elimination'], ['double elimination', 'double_elimination']].freeze

  FORMATS = [%w[singles singles],
             ['double draw your partner', 'double_draw_your_partner'],
             ['single draw your partner', 'single_draw_your_partner'],
             ['draw your partner, bring your partner', 'draw_your_partner_bring_your_partner'],
             ['single bring your partner', 'single_bring_your_partner']].freeze

  def winners_rounds
    hash = tournament_hash.dup
    hash.each_key do |key|
      next unless key.to_s.split('_').any? { |element| element == 'losers' }

      hash.delete(key)
    end
    hash
  end

  def losers_rounds
    hash = tournament_hash.dup
    hash.each_key do |key|
      next unless key.to_s.split('_').none? { |element| element == 'losers' }

      hash.delete(key)
    end
    hash
  end

  # rubocop:disable Metrics/MethodLength
  def fill_out_byes
    tournament_hash.each do |round|
      round.last.each do |match|
        next unless match.last.include?('bye')
        if match.last.all? { |teams| teams == 'bye' } && match.last.count == 2
          map_the_win(round.first.to_s, match.first.to_s, 'bye')
          map_the_loss(round.first.to_s, match.first.to_s, 'bye')
        elsif match.last.count == 2 && match.last.count { |e| e == 'bye' } == 1 && match.last.none?(&:blank?)
          winner = match.last.find { |team| team != 'bye' }
          next if winner.blank?
          map_the_win(round.first.to_s, match.first.to_s, winner)
          map_the_loss(round.first.to_s, match.first.to_s, winner)
        end
        save
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  def shrink_bracket
    tournament_hash.each do |round|
      tournament_hash.delete(round.first) if round.last.values.all? { |match| match.include?('bye') }
    end
    save
  end

  def map_the_win(round, match, winner, check_for_byes: false)
    winning_routes = winner_mapping_engine(round, match)
    tournament_hash.dig(winning_routes.first, winning_routes.second)[winning_routes.last] = winner
    advance_past_byes(winning_routes.first, winning_routes.second, winner) if check_for_byes
    save
  end

  def advance_past_byes(round, match, winner)
    return unless the_opponent_is_a_bye(round, match)

    map_the_win(round.to_s, match.to_s, winner, check_for_byes: true)
  end

  def the_opponent_is_a_bye(round, match)
    tournament_hash.dig(round, match).count == 2 &&
      tournament_hash.dig(round, match).count { |e| e == 'bye' } == 1
  end

  def map_the_loss(round, match, winner, check_for_byes: false)
    losing_team = tournament_hash.dig(round.to_sym, match.to_sym).find { |team| team != winner }
    return third_place_finish(losing_team) if round == 'losers_round_6'
    return if round.split('_').first == 'losers'

    losing_team = 'bye' if both_slots_are_byes(round, match)
    losing_routes = loser_mapping_engine(round, match, losing_team)
    if tournament_hash.dig(losing_routes.first, losing_routes.second).nil?
      advance_to_next_slot(losing_routes.first, losing_routes.second, losing_team)
    else
      tournament_hash.dig(losing_routes.first, losing_routes.second)[losing_routes.last] = losing_team
      advance_past_byes(losing_routes.first, losing_routes.second, losing_team) if check_for_byes
    end
    save
  end

  def third_place_finish(losing_team)
    results_hash[:third_place] = losing_team
    save
  end

  def advance_to_next_slot(round, match, winner)
    next_loser_routes = winner_mapping_engine(round.to_s, match.to_s)
    if tournament_hash.dig(next_loser_routes.first, next_loser_routes.second).nil?
      next_next_routes = winner_mapping_engine(next_loser_routes.first.to_s, next_loser_routes.second.to_s)
      tournament_hash.dig(next_next_routes.first, next_next_routes.second)[next_next_routes.last] = winner
    else
      tournament_hash.dig(next_loser_routes.first, next_loser_routes.second)[next_loser_routes.last] = winner
    end
    save
  end

  def create_unique_url
    update(unique_url: "#{created_at.strftime('%Y%m%d')}#{rand.to_s[2..11]}")
  end

  def destroy_challonge_tournament
    return if challonge_id.blank?

    ChallongeApi.delete_tournament(challonge_id)
  end

  def both_slots_are_byes(round, match)
    tournament_hash.dig(round.to_sym, match.to_sym).all? { |team| team == 'bye' } &&
      tournament_hash.dig(round.to_sym, match.to_sym).count == 2
  end

  def participants_count_is_ok
    return unless double_draw_your_partner?
    return if participants.count <= 16
    return if participants.count > 3

    errors.add(:base, 'Double draw your partner requires 16 or less participants') if participants.count <= 16
    errors.add(:base, 'Double draw your partsner requires 4 or more participants') if participants.count > 3
  end

  def participants_names_are_unique
    return if participants.count < 2
    array = participants.dup
    last = array.pop
    return unless array.map(&:downcase).include?(last.downcase)

    errors.add(:base, 'Names must be unique.')
  end

  def available_frequent_participants
    club.frequent_participants.map(&:downcase) - participants.map(&:downcase)
  end

  def setup_final(round, match, winner)
    if tournament_hash.dig(round.to_sym, match.to_sym).index(winner) == 1
      tournament_hash.dig(:round_6, :match_1)[0] = tournament_hash.dig(round.to_sym, match.to_sym)[0]
      tournament_hash.dig(:round_6, :match_1)[1] = tournament_hash.dig(round.to_sym, match.to_sym)[1]
    else
      results_hash[:first_place] = tournament_hash.dig(round.to_sym, match.to_sym)[0]
      results_hash[:second_place] = tournament_hash.dig(round.to_sym, match.to_sym)[1]
      update(status: 'finished')
    end
    save
  end

  def record_results(round, match, winner)
    loser = tournament_hash.dig(round.to_sym, match.to_sym).find { |player| player != winner }
    results_hash[:first_place] = winner
    results_hash[:second_place] = loser
    update(status: 'finished')
    save
  end

  # rubocop:disable Metrics/MethodLength
  def winner_mapping_engine(round, match)
    return [:round_2, :match_1, 0] if round == 'round_1' && match == 'match_1'
    return [:round_2, :match_1, 1] if round == 'round_1' && match == 'match_2'
    return [:round_2, :match_2, 0] if round == 'round_1' && match == 'match_3'
    return [:round_2, :match_2, 1] if round == 'round_1' && match == 'match_4'
    return [:round_2, :match_b_1, 0] if round == 'round_1' && match == 'match_b_1'
    return [:round_2, :match_b_1, 1] if round == 'round_1' && match == 'match_b_2'
    return [:round_2, :match_b_2, 0] if round == 'round_1' && match == 'match_b_3'
    return [:round_2, :match_b_2, 1] if round == 'round_1' && match == 'match_b_4'

    return [:round_3, :match_1, 0] if round == 'round_2' && match == 'match_1'
    return [:round_3, :match_1, 1] if round == 'round_2' && match == 'match_2'
    return [:round_3, :match_b_1, 0] if round == 'round_2' && match == 'match_b_1'
    return [:round_3, :match_b_1, 1] if round == 'round_2' && match == 'match_b_2'

    return [:round_4, :match_1, 0] if round == 'round_3' && match == 'match_1'
    return [:round_4, :match_1, 1] if round == 'round_3' && match == 'match_b_1'

    return [:round_5, :match_1, 0] if round == 'round_4' && match == 'match_1'

    return [:losers_round_2, :match_1, 0] if round == 'losers_round_1' && match == 'match_1'
    return [:losers_round_2, :match_2, 0] if round == 'losers_round_1' && match == 'match_2'
    return [:losers_round_2, :match_b_1, 0] if round == 'losers_round_1' && match == 'match_b_1'
    return [:losers_round_2, :match_b_2, 0] if round == 'losers_round_1' && match == 'match_b_2'

    return [:losers_round_3, :match_1, 0] if round == 'losers_round_2' && match == 'match_1'
    return [:losers_round_3, :match_1, 1] if round == 'losers_round_2' && match == 'match_2'
    return [:losers_round_3, :match_b_1, 0] if round == 'losers_round_2' && match == 'match_b_1'
    return [:losers_round_3, :match_b_1, 1] if round == 'losers_round_2' && match == 'match_b_2'

    return [:losers_round_4, :match_1, 0] if round == 'losers_round_3' && match == 'match_1'
    return [:losers_round_4, :match_b_1, 0] if round == 'losers_round_3' && match == 'match_b_1'

    return [:losers_round_5, :match_1, 0] if round == 'losers_round_4' && match == 'match_1'
    return [:losers_round_5, :match_1, 1] if round == 'losers_round_4' && match == 'match_b_1'

    return [:losers_round_6, :match_1, 0] if round == 'losers_round_5' && match == 'match_1'

    return [:round_5, :match_1, 1] if round == 'losers_round_6' && match == 'match_1'
    # finalize_results
  end

  def loser_mapping_engine(round, match, losing_team)
    return [:losers_round_1, :match_1, 0] if round == 'round_1' && match == 'match_1'
    return [:losers_round_1, :match_1, 1] if round == 'round_1' && match == 'match_2'
    return [:losers_round_1, :match_2, 0] if round == 'round_1' && match == 'match_3'
    return [:losers_round_1, :match_2, 1] if round == 'round_1' && match == 'match_4'
    return [:losers_round_1, :match_b_1, 0] if round == 'round_1' && match == 'match_b_1'
    return [:losers_round_1, :match_b_1, 1] if round == 'round_1' && match == 'match_b_2'
    return [:losers_round_1, :match_b_2, 0] if round == 'round_1' && match == 'match_b_3'

app/controllers/local_tournaments_controller.rb
class LocalTournamentsController < ApplicationController
  include TeamFormatterConcern

  after_action :allow_iframe, only: :show

  def index
    @local_tournaments = LocalTournament.all
  end

  def new
    @club = Club.find(params[:club_id])
    @local_tournament = @club.local_tournaments.build
  end

  def edit
    @tournament = LocalTournament.find(params[:id])
    redirect_to club_local_tournament_path(@tournament.club, @tournament) unless @tournament.signing_up?
  end

  # def show
  #   @tournament = LocalTournament.find(params[:id])
  #   @challonge_tournament = ChallongeApi.find_tournament(@tournament.challonge_id)
  #   @tournament_matches_by_round = ChallongeApi.find_matches(@tournament.challonge_id).select{ |match| match.dig('match', 'state') == 'open' }.group_by {|match| match['match']['round']}
  # end

  def show
    @tournament = LocalTournament.find(params[:id])
    @matches = @tournament.tournament_hash
  end

  def create
    @club = Club.find(params[:club_id])
    @local_tournament = @club.local_tournaments.new(local_tournaments_params)
    if @local_tournament.save
      redirect_to edit_club_local_tournament_path(@local_tournament.club, @local_tournament)
    else
      render 'new'
    end
  end

  def destroy
    @club = Club.find(params[:club_id])
    @local_tournament = LocalTournament.find(params[:id])
    @local_tournament.destroy
    redirect_to club_path(@club)
  end

  def submit_winner
    @local_tournament = LocalTournament.find(params[:local_tournament_id])
    round = match_params[:round_id]
    match = match_params[:match_id]
    winner = match_params[:winner]
    if round == 'round_5'
      @local_tournament.setup_final(round, match, winner)
    elsif round == 'round_6'
      @local_tournament.record_results(round, match, winner)
    else
      @local_tournament.map_the_win(round, match, winner, check_for_byes: true)
      @local_tournament.map_the_loss(round, match, winner, check_for_byes: true)
    end

    redirect_to club_local_tournament_path(@local_tournament.club, @local_tournament)
  end

  def all_local_tournaments
    @local_tournaments = LocalTournament.order(created_at: :desc)
  end

  def start_tournament
    @tournament = LocalTournament.find(params[:local_tournament_id])
    @tournament.update(tournament_hash: double_draw_your_partner(@tournament), status: LocalTournament.statuses[:started])
    4. times do # run 4 times because tournament_hash changes each time
      @tournament.fill_out_byes
    end
    @tournament.shrink_bracket
    redirect_to club_local_tournament_path(@tournament.club, @tournament)
  end

  # def generate_tournament
  #   tournament = LocalTournament.find(params[:local_tournament_id])
  #   return redirect_to club_local_tournament_path(tournament.club_id, tournament.id) if tournament.started?

  #   find_or_create_challonge_tournament(tournament)
  #   ChallongeApi.clear_out_participants(tournament.challonge_id)
  #   format_teams(tournament)
  #   challonge_bracket = ChallongeApi.start(tournament.challonge_id)
  #   tournament.update(status: LocalTournament.statuses[:started]) if challonge_bracket.parsed_response.dig('tournament', 'started_at').present?
  #   redirect_to club_local_tournament_path(tournament.club, tournament)
  # rescue TeamFormatterError => e
  #   redirect_to edit_club_local_tournament_path(tournament.club, tournament), alert: e
  # end

  def find_or_create_challonge_tournament(tournament)
    return ChallongeApi.find_tournament(tournament.challonge_id) if tournament.challonge_id.present?

    json_response = ChallongeApi.create_tournament(tournament)
    tournament.update(challonge_url: json_response.parsed_response.dig('tournament', 'live_image_url'),
                      challonge_id: json_response.parsed_response.dig('tournament', 'id'))
  end

  def update_challonge_tournament(tournament)
    ChallongeApi.update_tournament(tournament)
  end

  def enter_match_result
    tournament = LocalTournament.find(params[:local_tournament_id])
    scores_csv = '3-1,3-2'
    winner_id = params[:match_result][:winner].to_i
    ChallongeApi.update_match(tournament.challonge_id, params[:match_result][:match_id], winner_id, scores_csv)
    redirect_to club_local_tournament_path(tournament.club_id, tournament.id)
  end

  # def finalize
  #   tournament = LocalTournament.find(params[:local_tournament_id])
  #   ChallongeApi.finalize(tournament.challonge_id)
  #   tournament.update(status: LocalTournament.statuses[:finished])
  #   redirect_to club_local_tournament_path(tournament.club_id, tournament.id)
  # rescue ChallongeApiError => e
  #   redirect_to club_local_tournament_path(tournament.club_id, tournament.id), alert: e.errors.first
  # end

  private

  def match_params
    params.require(:match_result).permit(:round_id, :match_id, :winner)
  end

  def local_tournaments_params
    params.require(:local_tournament).permit(:name, :tournament_type, :format)
  end

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/helpers/local_tournaments_helper.rb
module LocalTournamentsHelper
end

app/views/local_tournaments/_players_form.html.slim
.subtitle.pb-2 Add Players

= form_for :players, url: club_local_tournament_participants_path(@tournament.club, @tournament) do |f|
  .row
    .col-8.col-md-6.col-sm-6.col-xs-6
      = f.text_field :name, required: true, autofocus: true, class: 'form-control'
    .col-4.col-md-6.col-sm-6.col-xs-6
      = f.submit 'Add Player', class: 'btn btn-outline-primary d-inline-block'

app/views/local_tournaments/edit.html.slim
- provide(:title, "Edit #{@tournament.name}")
- content_for :breadcrumbs
  li.breadcrumb-item = link_to 'Clubs', clubs_path
  li.breadcrumb-item = link_to "#{@tournament.club.name}: Tournaments", club_path(@tournament.club)
  li.breadcrumb-item.active Edit

= render partial: 'shared/errors', locals: { object: @tournament }

.container.py-4
  .row
    .col-6
      .subtitle Tournament
      h3 = @tournament.name.humanize
    .col-6
      i.fa.fa-cog.fa-2x.pt-4.float-right type='input' id='dropdownMenuButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
      .dropdown-menu aria-labelledby='dropdownMenuButton'
        - if @tournament.started?
          = link_to 'View Bracket', club_local_tournament_path(@tournament.club, @tournament), class: 'dropdown-item'
        - else
          / = link_to 'Start tournament', club_local_tournament_generate_tournament_path(@tournament.club, @tournament), class: 'dropdown-item py-3'
          = link_to 'Start tournament', club_local_tournament_start_tournament_path(@tournament.club, @tournament), class: 'dropdown-item py-3'
        = link_to 'Delete tournament', club_local_tournament_path(@tournament.club, @tournament), method: :delete, class: 'text-danger dropdown-item py-3'
  .row
    .col-lg-3.col-sm-6
      .subtitle Type
      h5 = @tournament.tournament_type.humanize
    .col-lg-3.col-sm-6
      .subtitle Format
      h5 = @tournament.format.humanize
    .col-lg-3.col-sm-6
      .subtitle Status
      h5 = @tournament.status.humanize

  = render 'local_tournaments/players_form'

  .pb-2
    - if @tournament.available_frequent_participants.any?
      .subtitle Frequent players
      - @tournament.available_frequent_participants.each do |participant|
        = link_to participant.titleize, club_local_tournament_participants_path(@tournament.club, @tournament, players: { name: participant }, frequent_list: true), method: :post, data: { disable_with: 'Please wait...'}, class: 'btn p-1 m-1 btn-outline-primary'

  - unless @tournament.participants.empty?
    .subtitle Players
    ol
      - @tournament.participants.each do |participant|
        li.pb-1
          div style='display:inline-block;width:150px;padding-right: 10px' = participant.titleize
          = link_to club_local_tournament_participant_path(@tournament.club, @tournament, participant), method: :delete, class: 'btn btn-sm py-1 px-2' do
            i.fa.fa-minus-circle.mr-1
            | remove

app/views/local_tournaments/show.html.slim
- content_for :breadcrumbs
  li.breadcrumb-item = link_to 'Clubs', clubs_path
  li.breadcrumb-item = link_to "#{@tournament.club.name}: Tournaments", club_path(@tournament.club)
  li.breadcrumb-item.active = @tournament.name

/ .large-bracket
/ <iframe src="#{@challonge_tournament['full_challonge_url']}/module?theme=6441&show_final_results=1&scale_to_fit=0" width="100%" height="700px" frameborder="0" scrolling="auto" allowtransparency="true"></iframe>
/ .mobile-bracket
/ <iframe src="#{@challonge_tournament['full_challonge_url']}/module?theme=6441&show_final_results=1&scale_to_fit=0&multiplier=0.9" width="100%" height="400px" frameborder="0" scrolling="auto" allowtransparency="true"></iframe>
/ <iframe src="#{@challonge_tournament.full_challonge_url}/module?theme=6441&show_final_results=1&multiplier=1.2" width="100%" height="1000px" frameborder="0" scrolling="auto" allowtransparency="true"></iframe>

/ .row
/   .col-12.col-md-6
/     .m-3
/       - if @tournament_matches_by_round.any?
/         h4 Matches
/         - @tournament_matches_by_round.each do |round|
/           h5 = round_name(round.first)
/           - round.last.each do |match|
/             .mt-2
              = form_for :match_result, url: club_local_tournament_enter_match_result_path(@tournament.club, @tournament, match.dig('match', 'id')) do |f|
                = f.hidden_field :match_id, value: match.dig('match', 'id')
                - player_one = ChallongeApi.find_participant(@tournament.challonge_id, match.dig('match', 'player1_id'))
                - player_two = ChallongeApi.find_participant(@tournament.challonge_id, match.dig('match', 'player2_id'))
                .btn-group.btn-group-toggle.w-75 data-toggle='buttons'
                  label.btn.btn-outline-secondary.w-50
                    = player_one['name']
                    = f.radio_button :winner, player_one['id']
                  label.btn.btn-outline-secondary.w-50
                    = player_two['name']
                    = f.radio_button :winner, player_two['id']

/                 = f.submit 'Submit', class: 'btn btn-outline-primary ml-2 pdf-2'

/ - unless @tournament_matches_by_round.any? || @tournament.finished?
/   = link_to 'finalize results', club_local_tournament_finalize_path(@tournament.club, @tournament), method: :post, class: 'btn btn-outline-primary green-outline' unless @tournament.finished?
/ = link_to 'Delete Tournament', club_local_tournament_path(@tournament.club, @tournament), method: :delete, class: 'm-3 btn btn-outline-primary' if current_user.try(:admin?)

/ - @matches = { round1: {match1: ['spenser', 'jeff'], match2: ['craig', 'corey'], match3: ['josh', 'sam'], match4: ['jill', 'sandy'] }, round2: { match1: ['jeff', 'corey'], match2: ['sam', 'jill']} }
/ - @matches = { round1: {match1: ['spenser', 'jeff'], match2: ['craig', 'corey'], match3: ['josh', 'sam'], match4: ['jill', 'sandy'], match5: ['spenser', 'jeff'], match6: ['craig', 'corey'], match7: ['josh', 'sam'], match8: ['jill', 'sandy'] }, round2: { match1: ['jeff', 'corey'], match2: ['sam', 'jill'], match3: ['jeff', 'corey'], match4: ['sam', 'jill']} }
/ - @matches = { round1: {match1: ['spenser', 'jeff'], match2: ['craig', 'corey'] }, round2: { match1: ['jeff', 'corey']} }

.winners-bracket
  - if @tournament.blank?
    p.mt-3.ml-3 Tournament has not been started yet
  - else
    h4.ml-3.my-2 Winners bracket
    - @tournament.winners_rounds.each.with_index(1) do |round, index|
      - unless round.first == :round_6 && round.last[:match_1].blank?
        .round class="round-#{index}"
          h6.text-center = round.first == :round_6 ? 'Grand Final' : round.first == :round_5 ? 'Final' : "Round #{index}"
          - round.last.each.with_index(1) do |match, index|
            .node class="#{index == 1 ? 'first-node' : 'next-nodes'}"
              .top class="#{'bye' if match.last[0] == 'bye'} #{did_this_player_win?(match.last[0], @tournament, round.first, match.first)}" = match.last[0] || '-'
              .bottom class="#{'bye' if match.last[1] == 'bye'} #{did_this_player_win?(match.last[1], @tournament, round.first, match.first)}" = match.last[1] || '-'
              - if match.last.any? { |player| player == 'bye'} || match.last.count < 2 || @tournament.finished?
                .node-submit
              - else
                = link_to club_local_tournament_path(@tournament.club, @tournament), 'data-toggle': 'modal', 'data-target': '#exampleModal', match: match.first, round: round.first, team_one: match.last[0], team_two: match.last[1], class: 'node-submit' do
                  i.fa.fa-edit
.losers-bracket.pt-3
  h4.ml-3 Losers bracket
  - @tournament.losers_rounds.each.with_index(1) do |round, index|
    .round class="#{round.first.to_s.gsub('_', '-')} index-#{index}"
      h6.text-center = "Losers round #{index}"
      - round.last.each.with_index(1) do |match, index|
        .node class="#{index == 1 ? 'first-node' : 'next-nodes'}"
          .top class="#{'bye' if match.last[0] == 'bye'} #{did_this_player_win?(match.last[0], @tournament, round.first, match.first)}" = match.last[0] || '-'
          .bottom class="#{'bye' if match.last[1] == 'bye'} #{did_this_player_win?(match.last[1], @tournament, round.first, match.first)}" = match.last[1] || '-'
          - if match.last.any? { |player| player == 'bye'} || match.last.count < 2 || @tournament.finished?
            .node-submit
          - else
              = link_to club_local_tournament_path(@tournament.club, @tournament), 'data-toggle': 'modal', 'data-target': '#exampleModal', match: match.first, round: round.first, team_one: match.last[0], team_two: match.last[1], class: 'node-submit' do
                i.fa.fa-edit

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select a winner</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        = form_for :match_result, url: club_local_tournament_submit_winner_path(@tournament.club, @tournament) do |f|
          = f.hidden_field :match_id, id: 'match-id'
          = f.hidden_field :round_id, id: 'round-id'
          .btn-group.btn-group-toggle.w-75 data-toggle='buttons'
            label.btn.btn-outline-secondary.w-50
              #label-one
              = f.radio_button :winner, '-', id: 'option-one'
            label.btn.btn-outline-secondary.w-50
              #label-two
              = f.radio_button :winner, '-', id: 'option-two'
          <div class="modal-footer mt-4">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            = f.submit 'Submit', class: 'btn btn-outline-primary ml-2 pdf-2'
          </div>
    </div>
  </div>
</div>

javascript:
  $('.node-submit').click(function() {
    $('#label-one').text($(this).attr('team_one'));
    $('#option-one').val($(this).attr('team_one'));
    $('#label-two').text($(this).attr('team_two'));
    $('#option-two').val($(this).attr('team_two'));
    $('#match-id').val($(this).attr('match'));
    $('#round-id').val($(this).attr('round'));
  })